# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcpanel1(wx.Panel):
#!XRCED:begin-block:xrcpanel1.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcpanel1.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PrePanel()
        self.PreCreate(pre)
        get_resources().LoadOnPanel(pre, parent, "panel1")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    testwxpython_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxPanel" name="panel1">
    <object class="wx.lib.foldpanelbar.FoldPanelBar"/>
    <object class="wxListBox" name="lstbox1">
      <content>
        <item>1234123</item>
        <item>sdfs</item>
        <item>456</item>
      </content>
    </object>
    <object class="wxListBox">
      <content>
        <item>123</item>
        <item>sdfgasdgdfgdfgdfg</item>
      </content>
    </object>
    <object class="wxGrid" name="g1">
      <pos>88,88</pos>
      <size>88,88</size>
    </object>
    <object class="wxButton" name="g1">
      <pos>88,88</pos>
      <size>88,88</size>
    </object>
    <pos>55</pos>
    <size>55</size>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/testwxpython/testwxpython_xrc', testwxpython_xrc)
    __res.Load('memory:XRC/testwxpython/testwxpython_xrc')


# ----------------------- Gettext strings ---------------------

def __gettext_strings():
    # This is a dummy function that lists all the strings that are used in
    # the XRC file in the _("a string") format to be recognized by GNU
    # gettext utilities (specificaly the xgettext utility) and the
    # mki18n.py script.  For more information see:
    # http://wiki.wxpython.org/index.cgi/Internationalization 
    
    def _(str): pass
    
    _("1234123")
    _("sdfs")
    _("456")
    _("123")
    _("sdfgasdgdfgdfgdfg")

